language: rust
os:
  - linux
  - windows
  - osx
rust:
  - nightly
branches:
  only:
    - master
script:
  - cargo build
  - cargo test --no-default-features --features tokio02
env:
  - RUST_BACKTRACE=1