language: rust
os:
  - linux
  - windows
  - osx
rust:
  - nightly
branches:
  only:
    - master
script:
  - cargo build --features tokio02
  - cargo test --features tokio02
env:
  - RUST_BACKTRACE=1