[package]
name = "leaky-bucket"
version = "0.8.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/leaky-bucket"
homepage = "https://github.com/udoprog/leaky-bucket"
documentation = "https://docs.rs/leaky-bucket"
description = """
Futures-aware rate limiter implementation.
"""
categories = ["algorithms", "network-programming", "concurrency"]

[dependencies]
futures-util = "0.3.1"
tokio = { version = "0.2.22", features = ["time", "stream", "sync"] }
log = "0.4.7"
lazy_static = { version = "1.4.0", optional = true }
thiserror = "1.0.9"

[features]
default = ["static"]
static = ["lazy_static", "tokio/rt-core"]

[dev-dependencies]
futures = "0.3.1"
tokio = { version = "0.2.4", features = ["macros", "rt-core"] }
